# Generated by Django 4.0 on 2023-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('photo', models.ImageField(upload_to='testimation/%Y/%m/%d/', verbose_name='Şəkil')),
                ('client_activate', models.CharField(max_length=255, verbose_name='Müəssisə')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Şərh tarxi')),
            ],
            options={
                'verbose_name': 'Şərh',
                'verbose_name_plural': 'Şərh',
            },
        ),
    ]
