# Generated by Django 4.0 on 2023-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Slayder adı')),
                ('description', models.TextField(verbose_name='Slayder məzmun')),
                ('image', models.ImageField(upload_to='slayder/%Y/%m/%d/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayder',
            },
        ),
    ]
