# Generated by Django 4.0 on 2023-09-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrangements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tərəfdaşlar adı')),
                ('image', models.ImageField(upload_to='partners/%Y/%m/%d/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Tərəfdaşlar',
                'verbose_name_plural': 'Tərəfdaşlar',
            },
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Məzmun')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon_business_plan', to='arrangements.icons', verbose_name='İkon')),
            ],
            options={
                'verbose_name': 'Biznes plan',
                'verbose_name_plural': 'Biznes plan',
            },
        ),
    ]
