# Generated by Django 4.0 on 2023-09-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_partners_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Tərəfdaşlar', 'verbose_name_plural': 'Tərəfdaşlar'},
        ),
        migrations.RemoveField(
            model_name='partners',
            name='name',
        ),
    ]
